-- ALCALDIA-RECURSOS-MUNICIPALES
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12200", "", "VENTA DE SERVICIOS DE LAS ADMINISTRACIONES PUBLICAS", "0", "PADRE", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12110", "122000-001", "VENTA DE SITIOS CEMENTERIO", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12210", "122000-002", "VALORES MUNICIPALES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, talonario_inicio, talonario_movimiento, talonario_final, precio, tipo, tenant, created_by, creation_date) VALUES ("12250", "122000-003", "TIMBRES", "9560", "9895", "9895", "1", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12260", "122000-004", "PASE DE INHUMACION / EXHUMACION", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12310", "122000-005", "VENTA DE SERVICIOS HOSPITALARIOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15113", "122000-006", "LIMPIEZA PUBLICA", "2", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12320", "", "VENTA DE MEDICAMENTOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12240", "122000-007", "RESOLUCION MUNICIPAL", "15", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13000", "", "INGRESOS TRIBUTARIOS", "0", "PADRE", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13310", "133000-001", "IMPUESTO A LA PROPIEDAD DE BIENES INMUEBLES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13330", "133000-002", "IMPUESTO A LA PROPIEDAD DE VEHICULOS AUTOMOTORES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13345", "133000-003", "IMPUESTO A LA TRANSFERENCIA DE BIENES INMUEBLES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13346", "", "IMPUESTO A LA TRANSFERENCIA DE  VEHICULOS AUTOMOTORES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13340", "133000-004", "IMPUESTO PRODUCCION DE CHICHA", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15100", "", "TASAS", "0", "PADRE", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15110", "15100-001", "APROBACION DE PLANOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15111", "15100-002", "VISACION DE MINUTAS", "25", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15112", "15100-003", "AUTORIZACION DE TRABAJOS MENORES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15114", "15100-004", "MINGITORIOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15115", "15100-005", "AFORACION DE PESAS Y MEDIDAS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15131", "15100-006", "REPOSICION DE COMPROBANTE", "2", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("23111", "", "APORTE VECINAL (ALCANTARILLADO F.N.D.R.)", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15100", "", "TAZA POR SERVICIO DE ALCANTARILLADO", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15340", "", "PATENTES", "0", "PADRE", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13351", "154000-001", "PATENTES DE FUNCIONAMIENTO", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13352", "154000-002", "PATENTE A LOS ESPECTACULOS PUBLICOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13354", "154000-003", "PATENTE A LA TRANSFORMACION DE GANADO", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("12220", "154000-004", "SENTAJE", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("13353", "154000-005", "PATENTE SOBRE FERIA KJAK`A LAWA", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15900", "", "OTROS INGRESOS NO TRIBUTARIOS PROPIOS", "46", "PADRE", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15510", "159000-001", "MULTAS Y RECARGOS", "46", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15520", "159000-002", "MULTAS POR MORA EN PAGO DE IMPUESTOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15900", "", "OTROS INGRESOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15990", "", "OTROS INGRESOS NO ESPECIFICADOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15311", "", "TALA DE ARBOLES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("23110", "", "APORTES BENEFICIARIOS", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15521", "", "MULTAS POR LETREROS IRREGULARES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("15410", "", "PEAJE (MEJORAMIENTO DE VIAS)", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("16500", "", "ALQUILERES", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");
INSERT INTO alcaldia_recursos_municipales (codigo, codigo_auxiliar, name, precio, tipo, tenant, created_by, creation_date) VALUES ("16501", "", "OTRAS CUENTAS A COBRAR A CORTO PLAZO", "0", "HIJO", "EMPRESA_1", "RecursosMunicipalesEncargado", "2021-11-01");

-- ALCALDIA-RECURSOS-MUNICIPALES_GRUPO
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12110' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12210' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
-- INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12250' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12260' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12310' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15113' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12320' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12200' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13000' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13310' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13000' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13330' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13000' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13345' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13000' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13346' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13000' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13340' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15110' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15111' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15112' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15114' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15115' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15131' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='23111' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TASAS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15100' AND name = 'TAZA POR SERVICIO DE ALCANTARILLADO' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13351' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13352' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13354' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='12220' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='13353' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15900' AND name = 'OTROS INGRESOS NO TRIBUTARIOS PROPIOS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15510' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_grupo (id_recurso_municipal_padre, id_recurso_municipal_hijo, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15900' AND name = 'OTROS INGRESOS NO TRIBUTARIOS PROPIOS' LIMIT 0, 1), (select id from alcaldia_recursos_municipales where codigo='15520' LIMIT 0, 1), "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");

-- ALCALDIA-RECURSOS-MUNICIPALES_VENTA
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ADRIANA_HERNANDEZ", "3390827", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ADRIANA_SANCHEZ", "1790656", "Colcapirhua", "", "ANULADO", "48" , "60", "12", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ALEJANDRO_ABONDANO", "8630841", "Colcapirhua", "", "ACTIVO", "10" , "30", "20", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ALEXANDER_CARVAJAL", "7992119", "Colcapirhua", "", "ANULADO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ANDRES_VILLA", "8952074", "Colcapirhua", "", "ACTIVO", "48" , "50", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("CAMILO_VILLAMIZAR", "7171467", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ALEJANDRO_FORERO", "8976966", "Colcapirhua", "", "ANULADO", "34" , "50", "16", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("GABRIEL_BUSTOS", "9193945", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ESTEBAN_BOTERO", "6119078", "Colcapirhua", "", "ACTIVO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("MARIO_OROZCO", "5526176", "Colcapirhua", "", "ACTIVO", "90" , "100", "10", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("GUILLERMO_ZUBIETA", "8559588", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("RICARDO_ZAMBRANO", "9265527", "Colcapirhua", "", "ACTIVO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("JOSE_GARCIA", "3848683", "Colcapirhua", "", "ACTIVO", "98" , "100", "20", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("LEONARDO_DUENAS", "2105023", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("YIRIAM_OCHOA", "1119730", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("YURANY_MENDEZ", "2519585", "Colcapirhua", "", "ANULADO", "40" , "50", "10", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("NATALIA_CONTRERAS", "3035904", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ANDREA_VELASCO", "3664558", "Colcapirhua", "", "ACTIVO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("MARIANA_SANTOS", "8060988", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("MARIA_MORENO", "3695400", "Colcapirhua", "", "ANULADO", "69" , "70", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("MARCELA_RUEDA", "6149557", "Colcapirhua", "", "ACTIVO", "82" , "100", "18", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("LISETH_VILLAMIL", "1818804", "Colcapirhua", "", "ANULADO", "56" , "100", "44", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("TATIANA_SIERRA", "2575825", "Colcapirhua", "", "ACTIVO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("LAURA_AYERBE", "2813910", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("LINA_RAMIREZ", "5203268", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ABRAHAM_ALANDIA", "1296705", "Colcapirhua", "", "ANULADO", "45" , "50", "5", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("HUGO_ROJAS", "6705735", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("REYNALDO_SEGALES", "1552512", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("EDDY_RIVERO", "9235689", "Colcapirhua", "", "ANULADO", "67" , "70", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ALFONSO_VILLAVICENCIO", "4726829", "Colcapirhua", "", "ACTIVO", "68" , "200", "132", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("PEDRO_precioYA", "5154533", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ROBERTO_BLADES", "", "Colcapirhua", "", "ACTIVO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("LUIS_VERA", "5464085", "Colcapirhua", "", "ACTIVO", "10" , "50", "40", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("MARCELO_ESTRADA", "6027347", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("FERNANDO_ARAMBURO", "6786256", "Colcapirhua", "", "ACTIVO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ALBERTO_LOPEZ", "8751865", "Colcapirhua", "", "ACTIVO", "300" , "1000", "700", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("LOURDES_ZEGALES", "6382097", "Colcapirhua", "", "ANULADO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("CAROL_VARGAS", "7527750", "Colcapirhua", "", "ANULADO", "18" , "30", "12", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("JUDITH_LOAYZA", "1646638", "Colcapirhua", "", "ACTIVO", "50" , "100", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ALICIA_CHAMBI", "3445853", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ALEJANDRO_AGUILAR", "3339047", "Colcapirhua", "", "ACTIVO", "25" , "50", "25", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("LUIS_ROSSEL", "4573009", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("GUSTAVO_APARICIO", "5208498", "Colcapirhua", "", "ANULADO", "100" , "200", "100", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("ADOLFO_ERGUETA", "8160319", "Colcapirhua", "", "ACTIVO", "25" , "50", "25", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("FERNANDO_DEHEZA", "9201192", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("RAMIRO_PINAYA", "3085683", "Colcapirhua", "", "ACTIVO", "16" , "30", "14", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("MARCOS_CASTELLON", "5786944", "Colcapirhua", "", "ANULADO", "25" , "50", "25", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("VERONICA_ZEBALLOS", "9686708", "Colcapirhua", "", "ACTIVO", "20" , "100", "80", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("RAQUEL_CLAVIJO", "8544316", "Colcapirhua", "", "ACTIVO", "250" , "300", "50", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date) VALUES ("PATTY_CANAVIRI", "6762800", "Colcapirhua", "", "ANULADO", "46" , "50", "4", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");

-- ALCALDIA-RECURSOS-MUNICIPALES_VENTA_DETALLE
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12110' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ADRIANA_HERNANDEZ'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12210' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='PATTY_CANAVIRI'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='VERONICA_ZEBALLOS'), "15", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='RAQUEL_CLAVIJO'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12260' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='MARCOS_CASTELLON'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='RAMIRO_PINAYA'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13351' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='FERNANDO_DEHEZA'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13352' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ADOLFO_ERGUETA'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15111' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='GUSTAVO_APARICIO'), "25", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15131' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='LUIS_ROSSEL'), "2", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12110' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ALEJANDRO_AGUILAR'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12210' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ALICIA_CHAMBI'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='JUDITH_LOAYZA'), "15", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='CAROL_VARGAS'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12260' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='LOURDES_ZEGALES'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ALBERTO_LOPEZ'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13351' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='FERNANDO_ARAMBURO'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13352' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='MARCELO_ESTRADA'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15111' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='LUIS_VERA'), "25", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15131' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ROBERTO_BLADES'), "2", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12210' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ALFONSO_VILLAVICENCIO'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='EDDY_RIVERO'), "15", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='REYNALDO_SEGALES'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12260' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='HUGO_ROJAS'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ABRAHAM_ALANDIA'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13351' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='LINA_RAMIREZ'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13352' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='LAURA_AYERBE'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15111' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='TATIANA_SIERRA'), "25", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15131' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='LISETH_VILLAMIL'), "2", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15111' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='MARCELA_RUEDA'), "25", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15131' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='MARIA_MORENO'), "2", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12110' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='MARIANA_SANTOS'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12210' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ANDREA_VELASCO'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='NATALIA_CONTRERAS'), "15", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='YURANY_MENDEZ'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12260' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='YIRIAM_OCHOA'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='LEONARDO_DUENAS'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13351' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='JOSE_GARCIA'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13352' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='RICARDO_ZAMBRANO'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15111' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='GUILLERMO_ZUBIETA'), "25", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15131' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='MARIO_OROZCO'), "2", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15111' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ESTEBAN_BOTERO'), "25", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='15131' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='GABRIEL_BUSTOS'), "2", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12110' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ALEJANDRO_FORERO'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12210' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='CAMILO_VILLAMIZAR'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ANDRES_VILLA'), "15", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12240' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ALEXANDER_CARVAJAL'), "0", "1", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-24");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='12260' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ALEJANDRO_ABONDANO'), "0", "2", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-25");
INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date) VALUES ((select id from alcaldia_recursos_municipales where codigo='13340' LIMIT 0, 1), (select id from alcaldia_recursos_municipales_venta where cliente_nombre='ADRIANA_SANCHEZ'), "0", "3", "EMPRESA_1", "RecursosMunicipalesEncargado", "2023-05-26");


DROP PROCEDURE IF EXISTS recursosMunicipalesAgregarVenta;
DELIMITER $$
CREATE PROCEDURE recursosMunicipalesAgregarVenta()
  BEGIN
    DECLARE totalRows INT DEFAULT 0;
    DECLARE indexRecursosMunicipales INT DEFAULT 0;
    SELECT COUNT(*) FROM alcaldia_recursos_municipales INTO totalRows;
    SET indexRecursosMunicipales=0;
    WHILE indexRecursosMunicipales < totalRows DO
      INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, created_by, creation_date)
      VALUES (
        "Cliente anonimo",
        "78877554",
        "Colcapirhua",
        "",
        "ACTIVO",
        FLOOR(RAND()*1000+1),
        FLOOR(RAND()*1000+1),
        FLOOR(RAND()*100+1),
        "EMPRESA_1",
        "RecursosMunicipalesEncargado",
        DATE_ADD('2023-05-25', INTERVAL indexRecursosMunicipales DAY));
      SET indexRecursosMunicipales = indexRecursosMunicipales + 1;
    END WHILE;
END; $$
DELIMITER ;
CALL recursosMunicipalesAgregarVenta();
DROP PROCEDURE recursosMunicipalesAgregarVenta;

DROP PROCEDURE IF EXISTS recursosMunicipalesAgregarDetalleVenta;
DELIMITER $$
CREATE PROCEDURE recursosMunicipalesAgregarDetalleVenta()
  BEGIN
    DECLARE totalRowsRecursosMunicipales INT DEFAULT 0;
    DECLARE totalRowsVentas INT DEFAULT 0;
    DECLARE indexProductos INT DEFAULT 0;
    DECLARE indexVentas INT DEFAULT 0;
    SELECT COUNT(*) FROM alcaldia_recursos_municipales WHERE name NOT LIKE "%TIMBRES%" INTO totalRowsRecursosMunicipales;
    SELECT COUNT(*) FROM alcaldia_recursos_municipales_venta INTO totalRowsVentas;
    SET indexProductos=0;
    WHILE indexProductos < totalRowsRecursosMunicipales DO
      SET indexVentas=0;
      WHILE indexVentas <  totalRowsVentas DO
        INSERT INTO alcaldia_recursos_municipales_venta_detalle(id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, created_by, creation_date)
        VALUES
            ((SELECT id FROM alcaldia_recursos_municipales WHERE name NOT LIKE "%TIMBRES%" LIMIT indexProductos, 1),
            (SELECT id FROM alcaldia_recursos_municipales_venta LIMIT indexVentas, 1),
            FLOOR(RAND()*10+1), -- Random de 1 a 10 cantidad.
            FLOOR(RAND()*100+1), -- Random de 1 a 100 precio unidad.
            "EMPRESA_1",
            "RecursosMunicipalesEncargado",
            DATE_ADD('2023-05-25', INTERVAL indexVentas DAY)),
            ((SELECT id FROM alcaldia_recursos_municipales WHERE name NOT LIKE "%TIMBRES%" LIMIT indexProductos, 1),
            (SELECT id FROM alcaldia_recursos_municipales_venta LIMIT indexVentas, 1),
            FLOOR(RAND()*10+1), -- Random de 1 a 10 cantidad.
            FLOOR(RAND()*100+1), -- Random de 1 a 100 precio unidad.
            "EMPRESA_1",
            "RecursosMunicipalesEncargado",
            DATE_ADD('2023-05-25', INTERVAL indexProductos DAY)),
            ((SELECT id FROM alcaldia_recursos_municipales WHERE name NOT LIKE "%TIMBRES%" LIMIT indexProductos, 1),
            (SELECT id FROM alcaldia_recursos_municipales_venta LIMIT indexVentas, 1),
            FLOOR(RAND()*10+1), -- Random de 1 a 10 cantidad.
            FLOOR(RAND()*100+1), -- Random de 1 a 100 precio unidad.
            "EMPRESA_1",
            "RecursosMunicipalesEncargado",
            '2023-05-25');
        SET indexVentas = indexVentas + 1;
      END WHILE;
      SET indexProductos = indexProductos + 1;
    END WHILE;
END; $$
DELIMITER ;
CALL recursosMunicipalesAgregarDetalleVenta();
DROP PROCEDURE recursosMunicipalesAgregarDetalleVenta;

INSERT INTO alcaldia_recursos_municipales_venta (cliente_nombre, cliente_ci_nit, direccion, nota, venta_status, venta_precio_total, cliente_dinero, cliente_cambio, tenant, creation_date, update_date, created_by, updated_by) VALUES 
('Jose antonio', '1111111', 'Colcapirhua', 'Desde el timbre  9560, Hasta el timbre  9575, ', 'ACTIVO', '15.00', '15.00', '0.00', 'EMPRESA_1', '2023-08-10 12:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('Carlos perez', '1211111', 'Colcapirhua', 'Desde el timbre  9575, Hasta el timbre  9595, ', 'ACTIVO', '20.00', '20.00', '0.00', 'EMPRESA_1', '2023-08-10 13:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('Rodrigo mendoza', '1121111', 'Colcapirhua', 'Desde el timbre  9595, Hasta el timbre  9650, ', 'ACTIVO', '55.00', '55.00', '0.00', 'EMPRESA_1', '2023-08-10 14:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('alfredo tapari', '1111211', 'Colcapirhua', 'Desde el timbre  9650, Hasta el timbre  9680, ', 'ACTIVO', '30.00', '30.00', '0.00', 'EMPRESA_1', '2023-08-10 15:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('rodolfo meldrano', '1111311', 'Colcapirhua', 'Desde el timbre  9680, Hasta el timbre  9700, ', 'ACTIVO', '20.00', '20.00', '0.00', 'EMPRESA_1', '2023-08-11 11:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('Jose antonio', '1311111', 'Colcapirhua', 'Desde el timbre  9700, Hasta el timbre  9740, ', 'ACTIVO', '40.00', '40.00', '0.00', 'EMPRESA_1', '2023-08-11 12:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('Carlos perez', '1111113', 'Colcapirhua', 'Desde el timbre  9740, Hasta el timbre  9770, ', 'ACTIVO', '30.00', '30.00', '0.00', 'EMPRESA_1', '2023-08-11 13:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('Rodrigo mendoza', '4111111', 'Colcapirhua', 'Desde el timbre  9770, Hasta el timbre  9799, ', 'ACTIVO', '29.00', '29.00', '0.00', 'EMPRESA_1', '2023-08-11 14:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('alfredo tapari', '1151111', 'Colcapirhua', 'Desde el timbre  9799, Hasta el timbre  9825, ', 'ACTIVO', '26.00', '26.00', '0.00', 'EMPRESA_1', '2023-08-12 11:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('rodolfo meldrano', '1161111', 'Colcapirhua', 'Desde el timbre  9825, Hasta el timbre  9860, ', 'ACTIVO', '35.00', '35.00', '0.00', 'EMPRESA_1', '2023-08-12 12:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('Carlos perez', '1111711', 'Colcapirhua', 'Desde el timbre  9860, Hasta el timbre  9880, ', 'ACTIVO', '20.00', '20.00', '0.00', 'EMPRESA_1', '2023-08-12 13:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('Rodrigo mendoza', '7111111', 'Colcapirhua', 'Desde el timbre  9880, Hasta el timbre  9892, ', 'ACTIVO', '12.00', '12.00', '0.00', 'EMPRESA_1', '2023-08-12 14:12:50', NULL, 'RecursosMunicipalesEncargado', NULL),
('alfredo tapari', '1181111', 'Colcapirhua', 'Desde el timbre  9892, Hasta el timbre  9895, ', 'ACTIVO', '3.00', '3.00', '0.00', 'EMPRESA_1', '2023-08-12 15:12:50', NULL, 'RecursosMunicipalesEncargado', NULL);

INSERT INTO alcaldia_recursos_municipales_venta_detalle (id_recurso_municipal, id_venta, precio_unidad, cantidad, tenant, creation_date, update_date, created_by, updated_by) VALUES
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1111111" LIMIT 0, 1),
'1.00', '15', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1211111" LIMIT 0, 1),
'1.00', '20', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1121111" LIMIT 0, 1),
'1.00', '55', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1111211" LIMIT 0, 1),
'1.00', '30', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1111311" LIMIT 0, 1),
'1.00', '20', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1311111" LIMIT 0, 1),
'1.00', '40', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1111113" LIMIT 0, 1),
'1.00', '30', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "4111111" LIMIT 0, 1),
'1.00', '29', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1151111" LIMIT 0, 1),
'1.00', '26', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1161111" LIMIT 0, 1),
'1.00', '35', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1111711" LIMIT 0, 1),
'1.00', '20', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "7111111" LIMIT 0, 1),
'1.00', '12', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL),
((SELECT id FROM alcaldia_recursos_municipales WHERE name LIKE "%TIMBRES%" LIMIT 0, 1),
(SELECT id FROM alcaldia_recursos_municipales_venta WHERE cliente_ci_nit LIKE "1181111" LIMIT 0, 1),
'1.00', '3', 'EMPRESA_1', '2023-08-10 23:12:52', NULL, 'RecursosMunicipalesEncargado', NULL);
