INSERT INTO acc_cuentas (codigo, name, created_by) VALUES
-- CUENTAS SIAT
('100000', 'ACTIVOS', 'SysAccountingAdmin'),
('110000', 'ACTIVOS CORRIENTES', 'SysAccountingAdmin'),
('111000', 'EFECTIVO Y/O SU EQUIVALENTE', 'SysAccountingAdmin'),
('111001', 'CAJA', 'SysAccountingAdmin'),
('111002', 'FONDO FIJO', 'SysAccountingAdmin'),
('111003', 'BANCOS', 'SysAccountingAdmin'),
('111004', 'INVERSIONES TEMPORALES', 'SysAccountingAdmin'),
('112000', 'CUENTAS POR COBRAR', 'SysAccountingAdmin'),
('112001', 'CUENTAS POR COBRAR COMERCIALES', 'SysAccountingAdmin'),
('112002', 'OTRAS CUENTAS POR COBRAR', 'SysAccountingAdmin'),
('112003', 'CUENTAS POR COBRAR A EMPRESAS RELACIONADAS', 'SysAccountingAdmin'),
('112004', 'ANTICIPO A PROVEEDORES', 'SysAccountingAdmin'),
('112005', 'PROVISION PARA CUENTAS INCOBRABLES', 'SysAccountingAdmin'),
('113000', 'INVENTARIOS', 'SysAccountingAdmin'),
('113001', 'INVENTARIOS DE PRODUCTOS TERMINADOS', 'SysAccountingAdmin'),
('113002', 'INVENTARIOS DE PRODUCTOS EN PROCESO', 'SysAccountingAdmin'),
('113003', 'INVENTARIOS DE MATERIA PRIMA', 'SysAccountingAdmin'),
('113004', 'INVENTARIO EN TRANSITO', 'SysAccountingAdmin'),
('113005', 'PROVISION PARA OBSOLESCENCIAS', 'SysAccountingAdmin'),
('114000', 'OTROS ACTIVOS CORRIENTES', 'SysAccountingAdmin'),
('114001', 'CREDITO FISCAL IVA', 'SysAccountingAdmin'),
('114002', 'IMPUESTOS POR RECUPERAR', 'SysAccountingAdmin'),
('114003', 'PAGOS ANTICIPADOS', 'SysAccountingAdmin'),
('114004', 'OTROS ACTIVOS', 'SysAccountingAdmin'),
('120000', 'ACTIVOS NO CORRIENTES', 'SysAccountingAdmin'),
('121000', 'CUENTAS POR COBRAR A LARGO PLAZO', 'SysAccountingAdmin'),
('121001', 'CUENTAS COMERCIALES POR COBRAR A LARGO PLAZO', 'SysAccountingAdmin'),
('121002', 'OTRAS CUENTAS POR COBRAR', 'SysAccountingAdmin'),
('121003', 'CUENTAS POR COBRAR A EMPRESAS RELACIONADAS', 'SysAccountingAdmin'),
('122000', 'INVENTARIOS NO CORRIENTES', 'SysAccountingAdmin'),
('122001', 'INVENTARIOS DE REPUESTOS', 'SysAccountingAdmin'),
('122002', 'OTROS INVENTARIOS', 'SysAccountingAdmin');
