package com.puggysoft.models;

public enum EnumCompareOperator {
  NONE,
  TEXT_EQUALS,
  TEXT_CONTAINS,
  TEXT_START_WITH,
  TEXT_END_WITH,
  DATE_BETWEEN,
  DATE_EQUALS,
  DATE_GREATER_EQUALS_THAN,
  DATE_GREATER_THAN,
  DATE_SMALLER_EQUALS_THAN,
  DATE_SMALLER_THAN,
  NUMBER_EQUALS,
  NUMBER_GREATER_EQUALS_THAN,
  NUMBER_GREATER_THAN,
  NUMBER_SMALLER_EQUALS_THAN,
  NUMBER_SMALLER_THAN,
  BOOLEAN_EQUALS
}
