// USERS SYSTEM
const ADMIN = "ADMIN";
const ADMIN_USERS = "ADMIN_USERS";
// HOSPITAL SYSTEM
const HOSPITAL_ADMIN = "HOSPITAL_ADMIN";
const HOSPITAL_DOCTOR = "HOSPITAL_DOCTOR";
const HOSPITAL_PATIENT = "HOSPITAL_PATIENT";
const HOSPITAL_TICKETS_ADMIN = "HOSPITAL_TICKETS_ADMIN";
// SALES SYSTEM
const SALES_ADMIN = "SALES_ADMIN";
const SALES_CLIENT = "SALES_CLIENT";
const SALES_SELLER = "SALES_SELLER";
const SALES_ADMIN_RESTAURANT = "SALES_ADMIN_RESTAURANT";
const SALES_SELLER_RESTAURANT = "SALES_SELLER_RESTAURANT";
const SALES_CLIENT_RESTAURANT = "SALES_CLIENT_RESTAURANT";
// SALES SYSTEM
const RESERVATION_ADMIN = "RESERVATION_ADMIN";
// ALCALDIA
const ALCALDIA_RECURSOS_MUNICIPALES_ENCARGADO = "ALCALDIA_RECURSOS_MUNICIPALES_ENCARGADO";
const ALCALDIA_RECURSOS_MUNICIPALES_CAJERO = "ALCALDIA_RECURSOS_MUNICIPALES_CAJERO";
const URBANISMO_ENCARGADO = "URBANISMO_ENCARGADO";
const REGULARIZACION_LOTES_ENCARGADO = "REGULARIZA_LOTES_ENCARGADO";
const REGULARIZACION_LOTES_CLIENTE = "REGULARIZA_LOTES_CLIENTE";
// DATA STORAGE
const STORAGE_ENCARGADO = "STORAGE_ENCARGADO";

const enumRoles = {
  // USERS SYSTEM
  ADMIN,
  ADMIN_USERS,
  // HOSPITAL SYSTEM
  HOSPITAL_ADMIN,
  HOSPITAL_DOCTOR,
  HOSPITAL_PATIENT,
  HOSPITAL_TICKETS_ADMIN,
  // SALES SYSTEM
  SALES_ADMIN,
  SALES_CLIENT,
  SALES_SELLER,
  // SALES SYSTEM RESTAURANT
  SALES_ADMIN_RESTAURANT,
  SALES_SELLER_RESTAURANT,
  SALES_CLIENT_RESTAURANT,
  // RESERVATION SYSTEM
  RESERVATION_ADMIN,
  // ALCALDIA
  ALCALDIA_RECURSOS_MUNICIPALES_ENCARGADO,
  ALCALDIA_RECURSOS_MUNICIPALES_CAJERO,
  URBANISMO_ENCARGADO,
  REGULARIZACION_LOTES_ENCARGADO,
  REGULARIZACION_LOTES_CLIENTE,
  // DATA STORAGE
  STORAGE_ENCARGADO
};

export default enumRoles;
