const CHART_HORIZONTAL_BAR = "CHART_HORIZONTAL_BAR";
const CHART_VERTICAL_BAR = "CHART_VERTICAL_BAR";
const CHART_LINE = "CHART_LINE";

const enumChartType = {
  CHART_HORIZONTAL_BAR,
  CHART_VERTICAL_BAR,
  CHART_LINE
};

export default enumChartType;
