const NONE = "NONE";
const TEXT_EQUALS = "TEXT_EQUALS";
const TEXT_CONTAINS = "TEXT_CONTAINS";
const TEXT_START_WITH = "TEXT_START_WITH";
const TEXT_END_WITH = "TEXT_END_WITH";
const DATE_BETWEEN = "DATE_BETWEEN";
const DATE_EQUALS = "DATE_EQUALS";
const DATE_GREATER_EQUALS_THAN = "DATE_GREATER_EQUALS_THAN";
const DATE_GREATER_THAN = "DATE_GREATER_THAN";
const DATE_SMALLER_EQUALS_THAN = "DATE_SMALLER_EQUALS_THAN";
const DATE_SMALLER_THAN = "DATE_SMALLER_THAN";
const NUMBER_EQUALS = "NUMBER_EQUALS";
const NUMBER_GREATER_EQUALS_THAN = "NUMBER_GREATER_EQUALS_THAN";
const NUMBER_GREATER_THAN = "NUMBER_GREATER_THAN";
const NUMBER_SMALLER_EQUALS_THAN = "NUMBER_SMALLER_EQUALS_THAN";
const NUMBER_SMALLER_THAN = "NUMBER_SMALLER_THAN";
const BOOLEAN_EQUALS = "BOOLEAN_EQUALS";

const enumCompareOperators = {
  NONE,
  TEXT_EQUALS,
  TEXT_CONTAINS,
  TEXT_START_WITH,
  TEXT_END_WITH,
  DATE_BETWEEN,
  DATE_EQUALS,
  DATE_GREATER_EQUALS_THAN,
  DATE_GREATER_THAN,
  DATE_SMALLER_EQUALS_THAN,
  DATE_SMALLER_THAN,
  NUMBER_EQUALS,
  NUMBER_GREATER_EQUALS_THAN,
  NUMBER_GREATER_THAN,
  NUMBER_SMALLER_EQUALS_THAN,
  NUMBER_SMALLER_THAN,
  BOOLEAN_EQUALS
};

export default enumCompareOperators;
